### ISSUE TITLE
No page on storage unit

### ISSUE THREAD

**Issue by andycolson93** [BG-Software-LLC/WildChests#214]
### Minecraft's Version

paper-1.20.2-309

### Plugin's Version

WildChests-2023.3-b27

### Describe the bug

Can't have multiple page with storage unit

### To Reproduce

config.yml 
```yml
  large_collector_storage_unit:
    chest-mode: STORAGE_UNIT
    size: 6
    title: Infinite Collector {0}
    item:
      name: '&aLarge chest collector 10 page infinit &7(Place to active)'
    pages:
      default: 10
      '1':
        title: 'Infinite Collector {0} #1'
      '2':
        title: 'Infinite Collector {0} #2'
      '3':
        title: 'Infinite Collector {0} #3'
      '4':
        title: 'Infinite Collector {0} #4'
      '5':
        title: 'Infinite Collector {0} #5' 
      '6':
        title: 'Infinite Collector {0} #6' 
      '7':
        title: 'Infinite Collector {0} #7' 
      '8':
        title: 'Infinite Collector {0} #8' 
      '9':
        title: 'Infinite Collector {0} #9'  
      '10':
        title: 'Infinite Collector {0} #10'  
    auto-suction:
      range: 5
      chunk: false
    particles:
      - TOTEM
```
