### ISSUE TITLE
deposit-method "SuperiorSkyblock2" not working

### ISSUE THREAD

**Issue by Franci47** [BG-Software-LLC/WildChests#241]
### Minecraft's Version

1.20.4

### Plugin's Version

#51 05/07/2024

### Describe the bug

I set deposit-method to SuperiorSkyblock2 but the money of my sellchest goes to sellchest placer instead of island bank account.

### To Reproduce

Don't know, just try., this is my config:
```
  sell_chest:
    chest-mode: CHEST
    size: 6
    title: '&bVendita automatica'
    item:
      name: '&dSell Chest &7(Place to active)'
    sell-mode: true  
    deposit-method: SuperiorSkyblock2
    particles:
      - SPELL_WITCH
```

### Additional Information

//
